---
title: "Workshops"
output:
  html_document:
    include:
      before_body: topbar_workshops.html
      after_body: footer.html
    css: styles_workshops.css
---


Most of the activities listed here are workshops organized either in the context
of research projects or as voluntary teaching activities.

<br/>

<div style="background-color: #ffe699; text-align: left; padding: 10px;
border-radius: 15px">

# Introduction to the package vegtable
*2017-03-09 Freiburg im Breisgau, Germany*

This workshop was offered during the
[**16<sup>th</sup> Meeting on Vegetation Databases**](https://www.hswt.de/person/joerg-ewald/vegetationsdatenbanken.html)
and includes an introduction to the packages `taxlist` and `vegtable`.

[**Handout**](workshops_freiburg_2017.html)

</div>

<br/>

<div style="background-color: #deefbc; text-align: left; padding: 10px;
border-radius: 15px">

# Storage and analysis of vegetation data: a crash course
*2016-11-18 Addis Ababa, Ethiopia*

A very quick introduction on the use of relational models (relational databases)
for the storage of vegetation data.
This activity was organized in the context of the project
[**ARBONETH**](https://www.arboneth.com).

[**Handout**](documents/Handout_ARBONETH_2016.pdf)

</div>

<br/>

<div style="background-color: #ffffcc; text-align: left; padding: 10px;
border-radius: 15px">

# Quick introduction to R and the Work with GIS
*2015-11-09 Addis Ababa, Ethiopia*

Workshop about R applications dealing with spatial data (GIS) and organized
within the activities of the project [**ARBONETH**](https://www.arboneth.com).

[**Handout**](documents/RandGIS.pdf)

</div>

<br/>